name: Build fonts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fontmake gftools
    - name: Build fonts
      run: |
        gftools builder sources/config.yaml
    - name: Archive fonts
      uses: actions/upload-artifact@v4
      with:
          name: ZenithSans
          path: |
            fonts/*
            OFL.txt
            README.md
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fontbakery
      - name: Download fonts
        uses: actions/download-artifact@v4
        with:
          name: ZenithSans
      - name: Test fonts on the Google Fonts suite
        run: |
          fontbakery check-googlefonts fonts/variable/*.ttf
          fontbakery check-googlefonts fonts/ttf/*.ttf
        
